# Generated by Django 2.2.7 on 2021-02-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20210216_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Year'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam'),
        ),
    ]
