# Generated by Django 2.2.7 on 2021-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191129_2238'),
        ('exam', '0013_auto_20210217_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned',
            field=models.ManyToManyField(to='user.Student'),
        ),
    ]
