# Generated by Django 2.2.7 on 2021-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_exam_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
