# Generated by Django 2.2.7 on 2021-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210217_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
