# Generated by Django 2.2.7 on 2021-02-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210217_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('start_date_time', 'exam_name')},
        ),
        migrations.AlterModelTable(
            name='exam',
            table='sınavlar',
        ),
    ]
