# Generated by Django 2.2.7 on 2021-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20210223_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_time',
            field=models.DurationField(default='00:05:00', help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', verbose_name='timeslot_duration'),
        ),
    ]
