# Generated by Django 2.2.7 on 2021-02-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20210223_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_time',
            field=models.TimeField(blank=True, help_text='Enter in minutes', null=True),
        ),
    ]
