# Generated by Django 2.2.7 on 2021-02-23 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20210223_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='available',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
