# Generated by Django 2.2.7 on 2021-02-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_exam_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='available',
        ),
    ]
