# Generated by Django 2.2.7 on 2021-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_remove_exam_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
