# Generated by Django 2.2.7 on 2021-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20210223_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_id',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
