# Generated by Django 2.2.7 on 2021-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_auto_20210223_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(default=1),
        ),
    ]
